
    // This code is generated by emlearn

    #include <eml_distance.h>
    

static const float packet_anomaly_detector_means[6] = { 57195.151879f, 19.040806f, 1216.529986f, 10.000000f, 9.040806f, 644.000000f };

static const float packet_anomaly_detector_precisions[36] = { 0.000000f, -0.000000f, -0.000000f, 0.000000f, -0.000000f, 0.000000f, -0.000000f, 0.000000f, 0.000004f, 0.000000f, 0.000000f, 0.000000f, -0.000000f, 0.000004f, 0.000263f, 0.000000f, 0.000004f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, -0.000000f, 0.000000f, 0.000004f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
    #include <stdio.h>

    // Data definitions
    static const EmlEllipticEnvelope final_model_classifier = {
        6,
        -179.21675724814207f,
		packet_anomaly_detector_means,
		packet_anomaly_detector_precisions
    };

    // Prediction function
    float packet_anomaly_detector_predict(const float *features, int n_features) {
        float dist = 0.0;
        const int class = eml_elliptic_envelope_predict(&final_model_classifier,
                                features, n_features, &dist);
        return dist; 
    }
    
