
    // This code is generated by emlearn

    #include <eml_distance.h>
    

static const float packet_anomaly_detector_means[6] = { 57799.731130f, 19.041080f, 1216.546933f, 10.000000f, 9.041080f, 644.000000f };

static const float packet_anomaly_detector_precisions[36] = { 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000004f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000004f, 0.000260f, 0.000000f, 0.000004f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000004f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
    #include <stdio.h>

    // Data definitions
    static const EmlEllipticEnvelope packet_anomaly_detector_classifier = {
        6,
        -4.409532134389547f,
        packet_anomaly_detector_means,
        packet_anomaly_detector_precisions
    };

    // Prediction function
    float packet_anomaly_detector_predict(const float *features, int n_features) {
        float dist = 0.0;
        const int class = eml_elliptic_envelope_predict(&packet_anomaly_detector_classifier,
                                features, n_features, &dist);
        return dist; 
    }
    